---
development:
  cloud_name: <%= ENV['CLOUDINATY_CLOUD_NAME'] %>
  api_key: <%= ENV["CLOUDINATY_API_KEY"] %>
  api_secret: <%= ENV['CLOUDINATY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV['CLOUDINATY_CLOUD_NAME'] %>
  api_key: '<%= ENV["CLOUDINATY_API_KEY"] %>'
  api_secret: <%= ENV['CLOUDINATY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV['CLOUDINATY_CLOUD_NAME'] %>
  api_key: '<%= ENV["CLOUDINATY_API_KEY"] %>'
  api_secret: <%= ENV['CLOUDINATY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
